// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/c_layer.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class CLayerBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  CLayerBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  CLayerBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void initialize(
    frame_callback frame_callback,
  ) {
    return _initialize(
      frame_callback,
    );
  }

  late final _initializePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(frame_callback)>>(
          'initialize');
  late final _initialize =
      _initializePtr.asFunction<void Function(frame_callback)>();

  void randomScreen(
    int seed,
  ) {
    return _randomScreen(
      seed,
    );
  }

  late final _randomScreenPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Uint64)>>(
          'randomScreen');
  late final _randomScreen = _randomScreenPtr.asFunction<void Function(int)>();
}

final class rgba extends ffi.Struct {
  @ffi.Uint8()
  external int r;

  @ffi.Uint8()
  external int g;

  @ffi.Uint8()
  external int b;

  @ffi.Uint8()
  external int a;
}

final class image extends ffi.Struct {
  @ffi.Uint64()
  external int width;

  @ffi.Uint64()
  external int height;

  external ffi.Pointer<rgba> pixels;
}

final class context extends ffi.Struct {
  external frame_callback frame_callback1;

  external image background;
}

typedef frame_callback
    = ffi.Pointer<ffi.NativeFunction<frame_callbackFunction>>;
typedef frame_callbackFunction = ffi.Void Function(ffi.Uint64 width,
    ffi.Uint64 height, ffi.Uint64 data_size, ffi.Pointer<ffi.Void> data);
typedef Dartframe_callbackFunction = void Function(
    int width, int height, int data_size, ffi.Pointer<ffi.Void> data);
