// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/c_layer.h`.
///
/// Regenerate bindings with `dart run ffigen --config ffigen.yaml`.
///
class CLayerBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  CLayerBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  CLayerBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void initialize(
    frame_callback frame_callback,
    int width,
    int height,
  ) {
    return _initialize(
      frame_callback,
      width,
      height,
    );
  }

  late final _initializePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              frame_callback, ffi.Uint64, ffi.Uint64)>>('initialize');
  late final _initialize =
      _initializePtr.asFunction<void Function(frame_callback, int, int)>();

  void update_background_color(
    int increment,
  ) {
    return _update_background_color(
      increment,
    );
  }

  late final _update_background_colorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int)>>(
          'update_background_color');
  late final _update_background_color =
      _update_background_colorPtr.asFunction<void Function(int)>();

  void update_background_size(
    int width,
    int height,
    int cycle_time,
    int x_offset,
    int y_offset,
  ) {
    return _update_background_size(
      width,
      height,
      cycle_time,
      x_offset,
      y_offset,
    );
  }

  late final _update_background_sizePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Uint64, ffi.Uint64, ffi.Uint64, ffi.Int64,
              ffi.Int64)>>('update_background_size');
  late final _update_background_size = _update_background_sizePtr
      .asFunction<void Function(int, int, int, int, int)>();

  void update_background_config(
    int config_byte,
  ) {
    return _update_background_config(
      config_byte,
    );
  }

  late final _update_background_configPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Uint8)>>(
          'update_background_config');
  late final _update_background_config =
      _update_background_configPtr.asFunction<void Function(int)>();

  void draw_background(
    int cycle_time,
    int x_offset,
    int y_offset,
  ) {
    return _draw_background(
      cycle_time,
      x_offset,
      y_offset,
    );
  }

  late final _draw_backgroundPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Uint64, ffi.Int64, ffi.Int64)>>(
      'draw_background');
  late final _draw_background =
      _draw_backgroundPtr.asFunction<void Function(int, int, int)>();

  void image_thread_entry_point(
    ffi.Pointer<image_settings> settings,
  ) {
    return _image_thread_entry_point(
      settings,
    );
  }

  late final _image_thread_entry_pointPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<image_settings>)>>(
      'image_thread_entry_point');
  late final _image_thread_entry_point = _image_thread_entry_pointPtr
      .asFunction<void Function(ffi.Pointer<image_settings>)>();

  void grid_configuration(
    ffi.Pointer<image_settings> settings,
  ) {
    return _grid_configuration(
      settings,
    );
  }

  late final _grid_configurationPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<image_settings>)>>(
      'grid_configuration');
  late final _grid_configuration = _grid_configurationPtr
      .asFunction<void Function(ffi.Pointer<image_settings>)>();

  void wave_configuration(
    ffi.Pointer<image_settings> settings,
  ) {
    return _wave_configuration(
      settings,
    );
  }

  late final _wave_configurationPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<image_settings>)>>(
      'wave_configuration');
  late final _wave_configuration = _wave_configurationPtr
      .asFunction<void Function(ffi.Pointer<image_settings>)>();

  bool is_index_in_range(
    int index,
    double base,
    range range,
  ) {
    return _is_index_in_range(
      index,
      base,
      range,
    );
  }

  late final _is_index_in_rangePtr = _lookup<
          ffi.NativeFunction<ffi.Bool Function(ffi.Int, ffi.Double, range)>>(
      'is_index_in_range');
  late final _is_index_in_range =
      _is_index_in_rangePtr.asFunction<bool Function(int, double, range)>();

  int round_double_to_int(
    double x,
  ) {
    return _round_double_to_int(
      x,
    );
  }

  late final _round_double_to_intPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Double)>>(
          'round_double_to_int');
  late final _round_double_to_int =
      _round_double_to_intPtr.asFunction<int Function(double)>();
}

abstract class configuration {
  static const int grid = 0;
  static const int wave = 1;
}

final class range extends ffi.Struct {
  @ffi.Double()
  external double offset;

  @ffi.Double()
  external double tolerance;
}

final class rgba extends ffi.Struct {
  @ffi.Uint8()
  external int r;

  @ffi.Uint8()
  external int g;

  @ffi.Uint8()
  external int b;

  @ffi.Uint8()
  external int a;
}

final class colors extends ffi.Struct {
  external rgba background_color;

  external rgba line_color;

  external rgba widget_color;
}

final class image_settings extends ffi.Struct {
  @ffi.Int32()
  external int config;

  @ffi.Uint64()
  external int cycle_time;

  @ffi.Uint64()
  external int x_offset;

  @ffi.Uint64()
  external int y_offset;

  @ffi.Uint64()
  external int start_row;

  @ffi.Uint64()
  external int end_row;
}

final class image_thread extends ffi.Struct {
  external image_settings settings;

  external thrd_t thread;
}

final class thrd_t extends ffi.Struct {
  external ffi.Pointer<ffi.Void> _Handle;

  @ffi.Uint32()
  external int _Tid;
}

final class image extends ffi.Struct {
  @ffi.Uint64()
  external int width;

  @ffi.Uint64()
  external int height;

  @ffi.Int32()
  external int config;

  external ffi.Pointer<rgba> pixels;
}

final class context extends ffi.Struct {
  external frame_callback frame_callback1;

  external colors colors1;

  external image background;

  @ffi.Uint8()
  external int num_image_threads;

  external ffi.Pointer<image_thread> image_threads;

  external mtx_t mutex;
}

typedef frame_callback
    = ffi.Pointer<ffi.NativeFunction<frame_callbackFunction>>;
typedef frame_callbackFunction = ffi.Void Function(ffi.Uint64 width,
    ffi.Uint64 height, ffi.Uint64 data_size, ffi.Pointer<ffi.Void> data);
typedef Dartframe_callbackFunction = void Function(
    int width, int height, int data_size, ffi.Pointer<ffi.Void> data);

final class mtx_t extends ffi.Struct {
  @ffi.UintPtr()
  external int _Type;

  external ffi.Pointer<ffi.Void> _Ptr;

  external ffi.Pointer<ffi.Void> _Cv;

  @ffi.Uint32()
  external int _Owner;

  @ffi.Uint32()
  external int _Cnt;
}

const int square_size = 150;

const int square_stroke_thickness = 2;

const int square_stroke_spacing = 50;
